src/main/java/com/gdg/z_meet/domain/user/entity/User.java, src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java, src/main/java/com/gdg/z_meet/domain/user/repository/UserProfileRepository.java, src/main/java/com/gdg/z_meet/domain/user/service/UserService.java, src/main/resources/application.yml
- feat/#13-user_profile
- 회원가입 시 유저 상세정보 받기
- 유저 상세정보 받기
- 유저와 유저프로필 관계매핑
-
=> [feat] 회원가입 시 유저 상세정보 받기

Dockerfile, build.gradle, docker-compse.yml, src/main/resources/application-prod.yml, src/main/resources/application.yml
- #2 
- application-prod.yml 환경 분리와, RDS 세팅을 하였습니다. 
- docker 구축을 위해 Dockerfile 과 docker-compose.yml 를 작성하였습니다. 
[Dockerfile] 
: jdk 및 jar 파일 빌드를 위한 설정, prod.yml 기준으로 빌드 되도록 설정 
[docker-compose.yml] 
:  개발 환경 db, redis 와 Dockerfile에서 설정해둔 jar 파일(배포 환경)을 각 각 컨테이너화 시켰고, 
gdg_network 내부에서 bridge 를 컨테이너 간 통신이 가능하도록 설정해두었습니다.  
추후 https 적용 및 리버스 프록싱을 위해 nginx 컨테이너가 추가 될 것 같고, 
빌드에 이상 없는지 아직 좀 더 테스트 해봐야할 것 같습니다.
- 
-
=> [chore] docker 구축 및 배포 환경 세팅

.github/workflows/gdg-ci-cd.yml
-  #20 
무중단 배포를 위한 CI-CD 파이프라인을 구축하였습니다. 
dev 와 main 에 Pull Request 가 생성되면 워크플로우가 작동하고, main 으로 최신화 시 최종적으로 운영 서버에 자동 배포 되도록 해놓았습니다.
-
=> [CI/CD] CI/CD 파이프라인 구축

src/main/java/com/gdg/z_meet/domain/booth/converter/BoothConverter.java, src/main/java/com/gdg/z_meet/domain/booth/dto/BoothResponseDTO.java
- fix/#33_account
- 부스배치도에 계좌 데이터 추가 반환
- GET /booths/{place} response 수정
- #33
=> [fix] 부스배치도 계좌 반환

src/main/java/com/gdg/z_meet/global/config/SecurityConfig.java
- 
- 프론트 대장님의 긴급한 요청 및 재촉
- cors url 추가
- 일부 설정 변경
=> [fix] CORS 수정 및 URL 추가

src/main/resources/db/migration/V2__Update_Set.sql
- #21 
- main 최신화 전 운영 환경 DB 마이그레이션 버전업을 하였습니다. 
- Entity 수정
=> [chore] 운영 환경 DB 마이그레이션 (Ver.2)

src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java, src/main/java/com/gdg/z_meet/domain/user/entity/enums/Major.java, src/main/java/com/gdg/z_meet/global/config/SecurityConfig.java
- feat/#35
- 학과 한글로 변환 후 response
- security에서 requestMatchers 바꾸지 않아 이번에 수정
- 학과 한글로 변환 후 response
- security에서 requestMatchers 바꾸지 않아 이번에 수정
- 이전에 풀리퀘 했던 내용에 security 설정이 추가되지 않아 먼저 풀리퀘 합니다.
=> #35 [feat] 학과 한글로 변환 후 보내기, security 수정

.github/workflows/gdg-ci-cd.yml, src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java, src/main/java/com/gdg/z_meet/domain/user/entity/enums/Major.java, src/main/java/com/gdg/z_meet/global/config/SecurityConfig.java, src/main/resources/application.yml, src/main/resources/db/migration/V2__Update_Set.sql
=> [chore] main 최신화

src/main/resources/db/migration/V3__Update_Set.sql
- #21 
- main 최신화 전 DB 마이그레이션을 진행하였습니다.
- 
-
=> [chore] main 최신화 전 DB 마이그레이션

src/main/java/com/gdg/z_meet/domain/user/dto/UserReq.java, src/main/java/com/gdg/z_meet/domain/user/dto/UserRes.java, src/main/java/com/gdg/z_meet/domain/user/entity/User.java, src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java, src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
- #64 
- 회원가입 시에 전화번호를 받기 -> 팀 생선 단계에서 팀원 초대시 사용
- 회원가입 시 전화번호 입력하기
- 전화번호로 user 검색하기
- 내 정보 조회 시에도 전화번호가 나오도록  수정
- #64
=> [Refactor] 회원가입 시 전화번호 받기

src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java, src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java, src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingRequestDTO.java, src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java, src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java, src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java, src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java, src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java, src/main/java/com/gdg/z_meet/global/exception/GlobalExceptionHandler.java, src/main/java/com/gdg/z_meet/global/response/Code.java
- feat/#67_search
- 미팅 2대2, 3대3 팀 만들기에서 팀원 검색하는 로직 구현
- GET /meeting/search API 개발
- nickname, phoneNumber 중 하나만 쿼리 파라미터로 입력해야 합니다.
- 닉네임은 1-8글자, 전화번호는 1-11글자 사이로 입력하지 않으면 에러 처리 하였습니다.
- 로그인 한 유저와 동성인 유저만 조회가 가능합니다.
- #67
=> [feat] 팀원 검색

src/main/resources/application-prod.yml, src/main/resources/db/migration/V4__Update_Set.sql
- #21 
- 
- 운영 서버에 반영할 DB를 마이그레이션 하였습니다.
-
=> [chore] DB 마이그레이션

src/main/java/com/gdg/z_meet/domain/user/dto/Token.java, src/main/java/com/gdg/z_meet/domain/user/dto/UserRes.java, src/main/java/com/gdg/z_meet/domain/user/entity/RefreshToken.java, src/main/java/com/gdg/z_meet/domain/user/entity/User.java, src/main/java/com/gdg/z_meet/domain/user/repository/RefreshTokenRepository.java, src/main/java/com/gdg/z_meet/domain/user/service/UserService.java, src/main/java/com/gdg/z_meet/global/config/SecurityConfig.java, src/main/java/com/gdg/z_meet/global/jwt/JwtAuthenticationFilter.java, src/main/java/com/gdg/z_meet/global/jwt/JwtUtil.java
- #69 
- 프로필 조회시 userid, gender 같이 반환, 로그인 시 userid 반환
- 프로필 조회시 userid, gender 같이 반환, 로그인 시 userid 반환
- #69
=> [refactor] 프로필 조회시 userid, gender 같이 반환, 로그인 시 userid 반환

src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
- #69 
- 학번 줄여서 반환할 때 숫자만
- 학번 줄여서 반환할 때 숫자만
- #69
=> 학번 줄여서 반환할 때 숫자만

src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java, src/main/java/com/gdg/z_meet/domain/user/dto/UserRes.java, src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
- #69 
- 내 프로필 조회시 회원 등급 같이 반환
- 내 프로필 조회시 회원 등급 같이 반환
- #69
=> 내 프로필 조회시 회원 등급 같이 반환

src/main/resources/db/migration/V5__Update_Set.sql
=> [chore] 운영 DB 마이그레이션

src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java, src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java, src/main/java/com/gdg/z_meet/domain/meeting/service/HiQueryServiceImpl.java, src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java, src/main/java/com/gdg/z_meet/domain/user/repository/UserProfileRepository.java
- Refactor/#91 chat hi
- 수정요청
- 하이 Controller Recevie 오타 수정
- 하이 목록 조회시 사용자별로 조회되도록 수정
- #91
=> Refactor: 하이 관련 코드 리팩토링

src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java, src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java, src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java, src/main/java/com/gdg/z_meet/domain/meeting/repository/HiRepository.java, src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java, src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java, src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
- refactor/#99_team-hi
- 팀 상세조회 시 하이 보낸 여부 반환하는 로직 구현
- GET /meeting/{teamId} API 응답에 하이 여부 추가
- #99
=> [refactor] 팀 상세조회 시 하이 보낸 여부 반환

src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java, src/main/java/com/gdg/z_meet/domain/user/dto/UserRes.java
- #108 
- userId 값 같이 반환하기
- 컨트롤러 빌드 -> dto 생성으로 변경
- userId 값 같이 반환하기
- 컨트롤러 빌드 -> dto 생성으로 변경
- #108
=> #108 [refactor] 컨트롤러 빌드 -> dto에서 생성으로

src/main/java/com/gdg/z_meet/global/config/WebSocketConfig.java
=> [chore] 운영 서버 최신화

src/main/java/com/gdg/z_meet/domain/user/entity/User.java, src/main/java/com/gdg/z_meet/domain/user/service/UserService.java, src/main/java/com/gdg/z_meet/global/jwt/JwtUtil.java
- #108 
- 배포환경에서의 오류 해결
- samesite설정
- #108
=> [fix] cookie 설정 변경

src/main/java/com/gdg/z_meet/global/jwt/JwtUtil.java
- #108 
- 쿠키 객체 사용이 없어 헤더에만 담기도록 수정
- 쿠키 객체를 생성하지 않도록 수정
- #108
=> [fix] 쿠키 객체 생성X

.github/workflows/gdg-ci-cd.yml, docker-compose.yml, nginx/nginx.conf
-  #72 
- 외부 트래픽으로부터 서버 최적화 
- WAS 컨테이너를 다중화하여, 외부 요청이 여러 컨테이너로 분산 처리 되도록 하였습니다. 테스트는 서버 최신화 후 Apache JMETER 를 통해 가상의 트래픽을 넣어 진행할 예정입니다. 
-
=> [chore] Nginx 웹 서버 로드밸런싱 적용

src/main/java/com/gdg/z_meet/domain/user/service/UserDetailsService.java, src/main/java/com/gdg/z_meet/domain/user/service/UserService.java, src/main/java/com/gdg/z_meet/global/config/SecurityConfig.java, src/main/java/com/gdg/z_meet/global/jwt/JwtAuthenticationFilter.java, src/main/java/com/gdg/z_meet/global/jwt/JwtUtil.java, src/main/resources/application.yml
- #108 
- 불필요한 요청들 줄이기 위해 수정
- 회원가입, 로그인 필터 거치지 않도록 수정
- userdetails 캐시 추가
- #108
=> [refactor] 회원가입, 로그인 필터X, userDetails 캐시추가

src/main/java/com/gdg/z_meet/domain/order/repository/KaKaoPayDataRepository.java, src/main/java/com/gdg/z_meet/domain/user/repository/UserProfileRepository.java, src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java, src/main/java/com/gdg/z_meet/global/config/MongoConfig.java, src/main/resources/application-prod.yml
=> [chore]  운영 서버 최신화

src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java, src/main/java/com/gdg/z_meet/domain/user/dto/UserRes.java, src/main/java/com/gdg/z_meet/domain/user/repository/UserProfileRepository.java, src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java, src/main/java/com/gdg/z_meet/domain/user/service/UserService.java, src/main/java/com/gdg/z_meet/global/response/Code.java
- #126 
- 회원가입 시 유저정보 중복여부 조회
- 닉네임, 학번, 전화번호 중복여부 조회
- #126
=> [feat] 유저정보 중복여부 조회

src/main/java/com/gdg/z_meet/domain/meeting/entity/Team.java, src/main/java/com/gdg/z_meet/domain/meeting/entity/enums/Event.java, src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java, src/main/java/com/gdg/z_meet/domain/meeting/repository/UserTeamRepository.java, src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java, src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java, src/main/java/com/gdg/z_meet/global/response/Code.java
- feat/#130_festival
- 행사마다 미팅 정보 리셋되도록 행사 정보 컬럼 추가
- 미팅 엔티티에 행사 정보 컬럼 추가
- #130
=> [feat] 행사 정보 추가

src/main/java/com/gdg/z_meet/domain/meeting/controller/EventController.java, src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java, src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java, src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandService.java, src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java, src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java, src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java, src/main/java/com/gdg/z_meet/global/config/SecurityConfig.java
- feat/#136_del-event
- 행사 부스용 팀 삭제 기회 늘려주는 로직 구현
- PATCH /event/leftDelete API 개발
- #136
=> [feat] 팀 삭제 기회 부스용

src/main/java/com/gdg/z_meet/domain/booth/controller/BoothController.java, src/main/java/com/gdg/z_meet/domain/booth/converter/BoothConverter.java, src/main/java/com/gdg/z_meet/domain/booth/dto/BoothRequestDTO.java, src/main/java/com/gdg/z_meet/domain/booth/entity/Place.java, src/main/java/com/gdg/z_meet/domain/booth/service/BoothCommandService.java, src/main/java/com/gdg/z_meet/domain/booth/service/BoothCommandServiceImpl.java, src/main/java/com/gdg/z_meet/domain/meeting/controller/EventController.java
- fix/#138_booths
- 부스 등록 api 수정
- POST /booths 수정
- 판매물품 추가
- #138
=> [fix] 부스 등록 api 수정

nginx/nginx.conf, src/main/resources/db/migration/V10__Update_Set.sql
=> [chore] DB 마이그레이션 

src/main/java/com/gdg/z_meet/domain/booth/dto/BoothRequestDTO.java, src/main/java/com/gdg/z_meet/domain/booth/entity/Club.java, src/main/java/com/gdg/z_meet/domain/booth/entity/Item.java, src/main/java/com/gdg/z_meet/global/jwt/JwtAuthenticationFilter.java
- fix/#142_booths
- POST /booths API JWT shouldNotFilter에 추가
- JwtAuthenticationFilter 수정
- 기타 validation 수정
- Club info 데이터타입 TEXT로 수정
- #142
=> [fix] 부스 등록 api JWT필터 수정

src/main/resources/db/migration/V11__Update_Set.sql
=> [chore] 운영 DB 마이그레이션 (Ver.11)

src/main/java/com/gdg/z_meet/domain/event/controller/EventController.java, src/main/java/com/gdg/z_meet/domain/event/service/EventService.java, src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandService.java, src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java, src/main/java/com/gdg/z_meet/domain/user/dto/UserRes.java, src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
- feat/#148_level
- 행사 부스용 ZI밋+ 등급 등록하는 로직 구현
- PATCH /event/level API 개발
- #148
=> [feat] ZI밋+ 등급 등록 부스용

src/main/java/com/gdg/z_meet/domain/chat/repository/ChatRoomRepository.java, src/main/java/com/gdg/z_meet/domain/chat/repository/JoinChatRepository.java, src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
- fix/#166_repository
- soft delete에 따른 레포지토리 수정
- Repository에 is_deleted 추가
- #166
=> [fix] soft delete에 따른 레포지토리 수정

src/main/java/com/gdg/z_meet/domain/chat/repository/JoinChatRepository.java, src/main/java/com/gdg/z_meet/domain/chat/service/ChatRoomCommandService.java, src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
- fix/#159-chatroom-remove-user
- 회원 탈퇴 기능 구현 
- 회원 탈퇴시 사용자의 모든 채팅방에서 나가기 처리 
- #159
=> [#159] Fix: 회원 탈퇴시 채팅방 나가기 처리

src/main/java/com/gdg/z_meet/domain/meeting/repository/MatchingRepository.java, src/main/java/com/gdg/z_meet/domain/meeting/service/RandomQueryServiceImpl.java
- fix/#168_random
- 랜덤미팅 현황 조회 에러 해결
- 랜덤미팅 마지막 참가자 현황 조회 에러 해결
- #168
=> [fix] 랜덤미팅 현황 조회 에러 해결

src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java, src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java, src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java, src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java, src/main/java/com/gdg/z_meet/domain/user/dto/UserRes.java, src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
- fix/#171_plus
- 지밋플러스 등급 적용 안되는 에러 해결
- 지밋플러스 등급 응답에 추가
- #171
=> [fix] 지밋플러스 조회 에러

src/main/java/com/gdg/z_meet/domain/meeting/repository/UserMatchingRepository.java, src/main/java/com/gdg/z_meet/domain/meeting/service/RandomCommandServiceImpl.java
- fix/#174_user-matching
- userMatching 삭제 안 되는 에러 해결
- cancelMatching 쿼리 수정
- #174
=> [fix] userMatching 삭제 안 되는 에러 해결

src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java, src/main/java/com/gdg/z_meet/domain/user/dto/UserReq.java, src/main/java/com/gdg/z_meet/domain/user/dto/UserRes.java, src/main/java/com/gdg/z_meet/domain/user/entity/User.java, src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java, src/main/java/com/gdg/z_meet/domain/user/service/UserService.java, src/main/java/com/gdg/z_meet/global/response/Code.java
- #184 
- 비밀번호를 잊어버렸을 때를 위한 비밀번호 찾기 구현
- 이름, 학번, 전화번호를 받고 검증 후 초기화 시킨다.
- 사용자가 원하는 비밀번호를 입력하고 추가 검증 후 변경한다.
-
=> [FEAT] 비밀번호 찾기 구현

src/main/resources/db/migration/V14__Update_Set.sql
- #21 
- DB 마이그레이션을 진행하였습니다. 
- `random_chat_id` 에 Unique 제약 조건이 추가되어서, 서버 최신화 시 DB 내 데이터에 중복된 값이 존재하면 오류가 나기에 추후 최신화 전 점검 필요합니다. (스스로에게 하는 말) 
-
=> [CHORE] DB Migration Ver.14

src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java, src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java, src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java, src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java, src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java, src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
- feat/#196_my-profile
- 1대1 미팅 참여 시 보여지는 내 프로필을 조회하는 로직 구현
- GET /meeting/myProfile API 개발
- #196 
프로필 올린 상태
프로필 내린 상태
=> [FEAT] 1대1 미팅 내 프로필 조회

src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java, src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java, src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java, src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java, src/main/java/com/gdg/z_meet/domain/user/repository/UserProfileRepository.java
- feat/#200_my-hi
- 1대1 미팅에서 하이 보낼 때 나의 남은 하이 개수 조회하는 로직 구현
- GET /meeting/myProfile/hi API 개발
- #200
=> [FEAT] 나의 남은 하이 개수

src/main/resources/db/migration/V14__Update_Set.sql
- #21 
- 
- DB Migration Ver.14 파일에 추가 사항이 있어서 반영하였습니다. 
-
=> [CHORE] DB Migration (Ver.14 추가본)

.github/workflows/gdg-ci-cd.yml
- #206 
- 
- CI 워크플로우 를 수정하고, 배포 과정에 로깅 처리를 하였습니다.
-
=> [CI/CD] CI 워크플로우 수정 및 로깅 추가

.gitignore, src/main/java/com/gdg/z_meet/domain/fcm/controller/FcmController.java, src/main/java/com/gdg/z_meet/domain/fcm/dto/FcmBroadcastReq.java, src/main/java/com/gdg/z_meet/domain/fcm/repository/FcmTokenRepository.java, src/main/java/com/gdg/z_meet/domain/fcm/service/FcmMessageClient.java, src/main/java/com/gdg/z_meet/domain/fcm/service/FcmService.java, src/main/java/com/gdg/z_meet/domain/fcm/service/FcmServiceImpl.java
- #208 
- 
- FCM 알림에 동의한 전체 User 들을 대상으로 보낼 FCM 알림 기능 구현
- 또한 토큰 만료에 대한 에러(`UNREGISTERED`) 처리 부분 수정
-
=> [FEAT] FCM 전체공지용 알림 기능 구현

.github/workflows/gdg-ci-cd.yml, .gitignore, src/main/java/com/gdg/z_meet/domain/fcm/controller/FcmController.java, src/main/java/com/gdg/z_meet/domain/fcm/dto/FcmBroadcastReq.java, src/main/java/com/gdg/z_meet/domain/fcm/repository/FcmTokenRepository.java, src/main/java/com/gdg/z_meet/domain/fcm/service/FcmMessageClient.java, src/main/java/com/gdg/z_meet/domain/fcm/service/FcmService.java, src/main/java/com/gdg/z_meet/domain/fcm/service/FcmServiceImpl.java
=> [CI/CD][CHORE] Deploy to Production Server 

src/main/java/com/gdg/z_meet/domain/fcm/entity/FcmToken.java, src/main/java/com/gdg/z_meet/domain/user/entity/User.java, src/main/resources/db/migration/V15__Update_Set.sql
- 
- 
- FcmToken 과 User 엔티티 연관 관계 수정
-
=> [CHORE] DB Migration Ver.15

src/main/java/com/gdg/z_meet/HealthCheckController.java, src/main/java/com/gdg/z_meet/domain/fcm/controller/FcmController.java, src/main/java/com/gdg/z_meet/domain/fcm/entity/FcmToken.java, src/main/java/com/gdg/z_meet/domain/fcm/repository/FcmTokenRepository.java, src/main/java/com/gdg/z_meet/domain/fcm/service/FcmMessageClient.java, src/main/java/com/gdg/z_meet/domain/fcm/service/FcmServiceImpl.java, src/main/java/com/gdg/z_meet/domain/user/entity/User.java, src/main/java/com/gdg/z_meet/global/response/Code.java, src/main/resources/db/migration/V15__Update_Set.sql
=> [CI/CD][CHORE] Deploy to Production Server

src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java, src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java, src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java, src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
- fix/#223_nickname
- 미팅 갤러리 조회 기능 리팩토링
- 1대1 미팅 갤러리에서 닉네임 반환하도록 수정
- 2대2 미팅 갤러리에 랜덤 정렬 적용
- #223
=> [FIX] 미팅 리팩토링

src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java, src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java, src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java, src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java, src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java, src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java, src/main/java/com/gdg/z_meet/global/response/Code.java
- feat/#225_detail
- 1대1 미팅 유저 프로필 상세조회 로직 구현
- GET /meeting/ONE_TO_ONE/{profileId} API 개발
- #225
=> [FEAT] 1대1 상세조회

src/main/java/com/gdg/z_meet/domain/chat/service/MessageCommandService.java, src/main/java/com/gdg/z_meet/domain/fcm/service/FcmServiceImpl.java, src/main/java/com/gdg/z_meet/domain/fcm/service/custom/FcmChatMessageService.java
- 
- 트랜잭션 분리 및 채팅 로직 관련 작업 분리로, FCM 전송 실패에 대한 대비
- 
-
=> [QA][REFACTOR] FCM  채팅 관련 알림 리팩토링 및 QA

src/main/java/com/gdg/z_meet/domain/chat/controller/ChatRoomController.java, src/main/java/com/gdg/z_meet/domain/event/service/EventService.java, src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java, src/main/java/com/gdg/z_meet/domain/meeting/controller/RandomController.java, src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java, src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
- refactor/#233_event
- 행사 정보 아우름제로 변경
- Event event = Event.AU_2025;
- #233
=> [REFACTOR] 행사 정보 아우름제로 변경

src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java, src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java, src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java, src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
- fix/#236_meeting
- 미팅 로직에 행사 정보 반영
- 미팅 참여, 조회 시 행사에 해당하는 데이터만 사용
- #236
=> [FIX] 미팅에 행사 정보 반영

src/main/java/com/gdg/z_meet/domain/event/Product.java, src/main/java/com/gdg/z_meet/domain/event/controller/EventController.java, src/main/java/com/gdg/z_meet/domain/event/dto/EventResponseDTO.java, src/main/java/com/gdg/z_meet/domain/event/service/EventService.java, src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java, src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java, src/main/java/com/gdg/z_meet/domain/user/repository/UserProfileRepository.java, src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
- feat/#239_booth
- 결제 확인 후 하이, 티켓 늘려주는 로직 부스용으로 구현
- 이름, 학번, 상품 선택하면 결제 반영
- #239
=> [FEAT] 부스용 결제

src/main/java/com/gdg/z_meet/domain/meeting/service/HiQueryServiceImpl.java
- fix/#244_hi
- 받은 하이에서 상대방 프로필 조회하도록 로직 수정
- GET /meeting/hiList/receive API 수정
- #244
=> [FIX] 받은 하이 프로필 에러

docker-compose.yml, src/main/java/com/gdg/z_meet/global/monitoring/check_containers.sh
- #253 
- 
- 30분 주기로 6개의 컨테이너에 대한 상태를 점검 후, 문제가 생길 시 디스코드 알림이 오도록 스크립트를 작성하였습니다. 
-
=> [FEAT][INFRA] Docker Container 상태 관리용 알림 기능 세팅
