build.gradle
src/main/java/com/gdg/z_meet/domain/booth/entity/Club.java
src/main/java/com/gdg/z_meet/domain/booth/entity/Item.java
src/main/java/com/gdg/z_meet/domain/chat/entity/ChatRoom.java
src/main/java/com/gdg/z_meet/domain/chat/entity/JoinChat.java
src/main/java/com/gdg/z_meet/domain/chat/entity/Message.java
src/main/java/com/gdg/z_meet/domain/meeting/entity/Hi.java
src/main/java/com/gdg/z_meet/domain/meeting/entity/Team.java
src/main/java/com/gdg/z_meet/domain/meeting/entity/UserTeam.java
src/main/java/com/gdg/z_meet/domain/order/entity/Orders.java
src/main/java/com/gdg/z_meet/domain/order/entity/TossPayments.java
src/main/java/com/gdg/z_meet/domain/user/entity/RefreshToken.java
src/main/java/com/gdg/z_meet/domain/user/entity/Terms.java
src/main/java/com/gdg/z_meet/domain/user/entity/User.java
src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
src/main/java/com/gdg/z_meet/domain/user/entity/UserTerms.java
src/main/resources/application-prod.yml
src/main/resources/application.yml
src/main/resources/db/migration/V1__Initial_Set.sql

- #21 
배포 환경에서의 DB 관리
JPA Hibernate 의 ddl-auto 는 validate 로 검증 용도로만 사용하고,
migration 라이브러리인 Flyway를 사용해서 운영 DB를 관리할 예정입니다.
8080 포트로 RDS 접근을 직접 못하게 막아놨기에, 머지 후 EC2에서 테스트 하겠습니다. 
+) hibernate가 자동으로 생성하는거 사용하도록 @Table 어노테이션 전부 제거하였습니다.

[chore] 운영 서버 DB Flyway 마이그레이션 적용

---

src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java
src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingRequestDTO.java
src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
src/main/java/com/gdg/z_meet/domain/meeting/entity/Team.java
src/main/java/com/gdg/z_meet/domain/meeting/entity/Verification.java
src/main/java/com/gdg/z_meet/domain/meeting/repository/MeetingRepository.java
src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
src/main/java/com/gdg/z_meet/domain/meeting/repository/UserTeamRepository.java
src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java
src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
src/main/java/com/gdg/z_meet/global/common/AuthenticatedUserUtils.java
src/main/java/com/gdg/z_meet/global/config/SwaggerConfig.java
src/main/java/com/gdg/z_meet/global/exception/GlobalExceptionHandler.java
src/main/java/com/gdg/z_meet/global/response/Code.java

- feat/#19_team-gallery
- 2대2, 3대3 미팅 팀 소개(상세조회) 구현
- GET /meeting/{teamId} API 개발
- 지밋 플러스 검증은 추후 개발할 예정입니다.
- 본인이 포함된 팀은 조회가 불가능합니다. GET /meeting/myTeam 으로만 조회하도록 구현할 예정입니다.
- AuthenticatedUserUtils로 로그인 한 유저의 정보를 검증하는 코드를 작성하였습니다. 이 부분 확인하고 피드백 주시면 감사하겠습니다 :)
- #19

[feat] 미팅 팀 소개 구현

---

src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java
src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java
src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
src/main/java/com/gdg/z_meet/global/exception/GlobalExceptionHandler.java

- feat/#45_my-team
- 2대2, 3대3 미팅 우리팀 소개(상세 조회) 로직 구현
- GET /meeting/myTeam API 개발
- GET /meeting/myTeam/detail API 개발
- 팀 타입마다 유저가 속한 팀이 2개 이상일 경우 에러가 발생합니다!
팀 생성 로직에서, 팀 타입당 한 팀씩만 생성할 수 있도록 구현할 예정이라서 별도의 처리 없이 진행하였습니다 :)
- #45

[feat] 우리팀 소개 구현

---

src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java
src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java

- feat/#49_team-name
- 팀 생성하기 시, 팀명 중복확인 기능 구현
- 팀명 검색 GET /meeting/name API 개발
- 프론트와 협의해서 요청 응답을 Integer(0-중복, 1-중복 아님)로 보내주도록 개발하였습니다.
- 글자수 제한(1~7글자)
- #49

[feat] 팀명 중복확인 기능 구현

---

src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java

- #51 
- 팀 갤러리 조회 시, 전공, 음악 중복처리
- GET /meeting 반환 시 distinct 옵션 추가
- #51

[refactor] 팀 전공, 음악 중복처리

---

src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java
src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingRequestDTO.java
src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
src/main/java/com/gdg/z_meet/domain/meeting/repository/UserTeamRepository.java
src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandService.java
src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java
src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
src/main/java/com/gdg/z_meet/global/exception/GlobalExceptionHandler.java
src/main/java/com/gdg/z_meet/global/response/Code.java

- feat/#54_team-create
- 미팅 2대2, 3대3 팀 만들기 로직 구현
- POST /meeting/myTeam API 개발
- getTeamGallery 메서드 분리
- getPreMyTeam 응답에 null 추가
- #54

[feat] 팀 만들기 구현

---

src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java
src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
src/main/java/com/gdg/z_meet/domain/meeting/repository/UserTeamRepository.java
src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandService.java
src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java
src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java
src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
src/main/java/com/gdg/z_meet/domain/user/repository/UserProfileRepository.java
src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
src/main/java/com/gdg/z_meet/global/exception/GlobalExceptionHandler.java
src/main/java/com/gdg/z_meet/global/response/Code.java

- feat/#63_team-del
- 2대2, 3대3 미팅 팀 삭제 로직 구현
- DELETE /meeting/myTeam API 개발
- 팀 생성 시 userTeam 저장 안 되는 문제 해결
- 엔티티에 수정 사항이 있기 때문에, 테스트할 때 디비 업데이트 해주셔야 에러 안 납니닷
기존 deleteTeam -> leftDelete
- 해당 팀 내에서 삭제 기회가 0인 팀원이 존재할 경우, DELETE_LIMIT_EXCEEDED 에러가 발생합니다.
- GET /meeting/myTeam/delete API 개발
- #63

[feat] 미팅 팀 삭제

---

.gitignore
src/main/java/com/gdg/z_meet/domain/meeting/controller/RandomController.java
src/main/java/com/gdg/z_meet/domain/meeting/converter/RandomConverter.java
src/main/java/com/gdg/z_meet/domain/meeting/dto/RandomResponseDTO.java
src/main/java/com/gdg/z_meet/domain/meeting/service/RandomQueryService.java
src/main/java/com/gdg/z_meet/domain/meeting/service/RandomQueryServiceImpl.java
src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java

- feat/#70_ticket
- 랜덤미팅 남은 티켓 개수 조회하는 로직 구현
- GET /random/ticket API 개발
- #70

랜덤미팅 남은 티켓 개수 조회하는 로직 구현

---

src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
src/main/java/com/gdg/z_meet/domain/meeting/service/HiQueryServiceImpl.java

- fix#88-hi-dto
-  하이 dto 수정
- 하이 조회시 상대방 팀과 내 팀 ID를 조회할 수 있도록 수정 (보낸하이/받은하이)
- #88

[Fix] #88: 하이 조회시 상대방 팀과 내 팀 ID를 조회할 수 있도록 수정

---

src/main/java/com/gdg/z_meet/domain/chat/service/ChatRoomQueryService.java

- fix/#100-chatroom-users-read
- 프론트파트장님 요청
- 채팅방 내 사용자 조회시 상대방 이름이 나오는 오류수정
- #100

[#100] Fix: 채팅방 내 사용자 조회시 상대방 이름이 나오는 오류수정

---

src/main/java/com/gdg/z_meet/domain/chat/service/ChatRoomQueryService.java

- fix#104-chatroom-user-list
- 프론트팀장님 요청
- 사용자 조회시 닉네임이 조회되도록 설정
- #104

[#104] Fix: 사용자 조회시 닉네임이 조회되도록 설정

---

src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java
src/main/java/com/gdg/z_meet/domain/user/dto/UserRes.java

- #108 
- 액세스 만료 시 리프레쉬를 이용해 액세스 발급하는 api 추가
- 액세스가 존재 시 로그인 중임을 반환
- 액세스가 만료된 상태에서 쿠키에 있는 리프레쉬를 이용해 액세스 재발급 후 로그인 중임을 확인
- #108

#108 [feat] 로그인 상태확인 api 구현

---

src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java
src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java

- fix/#107_team-search
- 미팅 2대2, 3대3 팀 생성 시 팀원 추가(검색) 로직 수정
- /meeting/search API 수정
- 본인 조회 안 되도록 수정
- 팀 존재하는 유저 조회 안 되도록 수정
- 검색어 포함 데이터 X, 검색어로 시작하는 데이터만 조회되도록 수정
- #107 
014be6980" />

[fix] 팀원 추가 로직 수정

---

src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java
src/main/java/com/gdg/z_meet/domain/user/repository/RefreshTokenRepository.java
src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
src/main/java/com/gdg/z_meet/global/config/SecurityConfig.java
src/main/java/com/gdg/z_meet/global/jwt/JwtAuthenticationFilter.java
src/main/java/com/gdg/z_meet/global/jwt/JwtUtil.java

- #119 
- 리프레시 토큰 저장이 필요해져 재구현
- 리프레시 레디스에 저장
- 리프레시만 있을 때 api 실행 시 액세스를 header -> authorization으로 넣어 검증
- #119

[feat] 리프레시 토큰 DB에 저장

---

src/main/java/com/gdg/z_meet/domain/meeting/entity/Team.java
src/main/java/com/gdg/z_meet/domain/meeting/entity/enums/ActiveStatus.java
src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
src/main/java/com/gdg/z_meet/domain/meeting/repository/UserTeamRepository.java
src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java
src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
src/main/java/com/gdg/z_meet/domain/order/service/KaKaoPayService.java
src/main/java/com/gdg/z_meet/global/response/Code.java

- feat/#122_team-status
- 팀 엔티티에 상태 컬럼 추가
- 팀이 삭제되어도 채팅은 남아있어야 하기 때문에 ActiveStatus enum 추가
- 채팅 로직 제외하고, ACTIVE한 팀만 조회하도록 수정
- 팀 삭제 요청 시 INACTIVE로 변경됨
- #122

[feat] 팀 상태 컬럼 추가

---

src/main/java/com/gdg/z_meet/domain/chat/service/ChatRoomQueryService.java
src/main/java/com/gdg/z_meet/domain/meeting/entity/enums/HiStatus.java
src/main/java/com/gdg/z_meet/domain/meeting/repository/HiRepository.java
src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingCommandServiceImpl.java

- refacotr/#131-hi
- 팀은 삭제할때 하이도 같이 삭제되도록 구현 
- 채팅 사용자 조회할 때 우리팀이 먼저 조회될때도 있고 나중에 조회될때도 있음 
- 하이 DELETED 상태 추가 및 팀 삭제시 하이도 삭제하도록 구현
- 채팅 사용자 조회할 때 우리팀이 먼저 조회되도록 설정
- 팀을 넘길때 이성팀/내팀이 아니라 이성/내로 넘기도록 수정 
- #131

[Refactor] 하이 삭제 구현

---

src/main/java/com/gdg/z_meet/global/jwt/JwtAuthenticationFilter.java
src/main/java/com/gdg/z_meet/global/jwt/JwtUtil.java

- #144 
클라이언트가 API를 호출 시나, RefreshToken이 없을 경우 계속해서 doFilterInternal()이 호출되며, 토큰 검증 과정이 매 요청마다 수행 되었었는데, `Set<String>`을 사용하여 이미 로그를 출력한 토큰을 저장하여 로그 상태를 저장하고, 재출력 되지 않도록 리팩토링 하였습니다.
- 
- #144

[refactor] 토큰 검증 과정 리팩토링

---

src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java

- fix/#154_search
- 팀 삭제를 soft delete로 구현함에 따라 팀원 조회 로직 수정
- active인 팀이 존재하지 않는 유저 검색하도록 수정
- #154

[fix] 팀원 조회 로직 수정

---

docker-compose.yml
src/main/java/com/gdg/z_meet/domain/chat/controller/ChatRoomController.java
src/main/java/com/gdg/z_meet/domain/chat/dto/ChatRoomDto.java
src/main/java/com/gdg/z_meet/domain/chat/entity/ChatRoom.java
src/main/java/com/gdg/z_meet/domain/chat/entity/status/ChatType.java
src/main/java/com/gdg/z_meet/domain/chat/repository/JoinChatRepository.java
src/main/java/com/gdg/z_meet/domain/chat/service/ChatRoomCommandService.java
src/main/java/com/gdg/z_meet/domain/chat/service/ChatRoomQueryService.java
src/main/java/com/gdg/z_meet/domain/chat/service/MessageCommandService.java
src/main/java/com/gdg/z_meet/domain/chat/service/MessageQueryService.java
src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingRequestDTO.java
src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
src/main/java/com/gdg/z_meet/domain/meeting/entity/Hi.java
src/main/java/com/gdg/z_meet/domain/meeting/entity/enums/HiType.java
src/main/java/com/gdg/z_meet/domain/meeting/repository/HiRepository.java
src/main/java/com/gdg/z_meet/domain/meeting/service/HiCommandService.java
src/main/java/com/gdg/z_meet/domain/meeting/service/HiCommandServiceImpl.java
src/main/java/com/gdg/z_meet/domain/meeting/service/HiQueryService.java
src/main/java/com/gdg/z_meet/domain/meeting/service/HiQueryServiceImpl.java
src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
src/main/java/com/gdg/z_meet/domain/meeting/service/RandomCommandServiceImpl.java
src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java
src/main/java/com/gdg/z_meet/global/response/Code.java

- Feat/#178-chat
- 1:1 하이, 채팅방 기능 추가 
- 2:2 랜텀미팅 수정 
- 1:1 하이 기능 추가 -> hi 엔티티에서 hi_type 필드 추가 ("USER", "TEAM") 
- 1:1 채팅 기능 추가 -> chat_room 엔티티에서 chat_type 변경("USER" 추가됨)
- 예시 코드) `ALTER TABLE chat_room MODIFY COLUMN chat_type ENUM('RANDOM', 'TEAM', 'USER') NOT NULL;`
- 2:2 랜덤미팅으로 수정
- 랜덤미팅 방 id를 db에서 조회하는 것이 아닌 레디스에 저장해서 조회하도록 수정. 만약 레디스에 값이 없을 경우 db 조회
- 채팅 메시지 모두 몽고db에 저장. 최근 메시지는 레디스에서 가져옴.
- 그 외 코드 리팩토링 (중복 코드 하나로 합치기 등) 
- #178

[FEAT, REFACTOR] 하이,채팅 1:1 추가 및 코드 리팩토링 

---

.gitignore
build.gradle
src/main/java/com/gdg/z_meet/global/config/WebConfig.java
src/main/java/com/gdg/z_meet/global/jwt/AuthUserArgumentResolver.java
src/main/java/com/gdg/z_meet/global/jwt/JwtUtil.java
src/main/java/com/gdg/z_meet/global/security/AuthUser.java

- 
- 인증된 사용자의 정보 주입 방식 커스텀
`Long userId = AuthenticatedUserUtils.getAuthenticatedUserId();` 기존에는 유틸 클래스를 컨트롤러 내부에서 직접 호출해 SecurityContext에서 ID 추출하는 방식을 사용해왔는데,
해당 방식은 컨트롤러 내부에서 인증 정보를 다뤄야 하므로 SRP에 맞지 않았고, 테스트 코드 작성 시, SecurityContext 를 구성해줘야하므로 Mocking이 불가능한 단점이 있다고 판단되어, 커스텀 어노테이션 `@AuthUser` 를 구현하였습니다.
사용 방법은 `@AuthUser User user` 처럼 컨트롤러 파라미터로 주입해서 사용하시면 됩니다. 
-

[FEAT] Controller 사용자 인증 처리 로직 커스터마이징

---

build.gradle
src/main/java/com/gdg/z_meet/domain/fcm/controller/FcmController.java
src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java
src/main/java/com/gdg/z_meet/domain/user/dto/UserReq.java
src/main/java/com/gdg/z_meet/domain/user/service/UserService.java
src/test/java/com/gdg/z_meet/service/FcmServiceImplTest.java

- #187 
- 
1. 기존에 백엔드 내에서 쿠키 만료를 통해 로그아웃을 진행하였는데, 현재 디바이스의 토큰에 대해서만 삭제가 필요하므로, 프론트 측에서 FCM 토큰 값을 받아오도록 하여 로그아웃 시, 사용자의 FCM 토큰이 유효하다면 삭제합니다. 
DB 에서 FCM 토큰을 꺼내는 방식을 택하지 않은 이유는 아래와 같습니다.
- JWT에는 디바이스 정보가 없음.
- DB에서 모든 토큰을 조회(특정 디바이스 식별이 안되기 때문)하여 삭제하면 다른 디바이스의 푸시까지 차단되는 이슈가 생김
- 서버는 클라이언트가 알려주는 FCM 토큰만을 삭제하면 되므로, 책임 분리 명확
2. FCM에 대한 테스트는 별도의 테스트 토큰 없이 실제 디바이스 환경에서 진행해야 하기에, Mocking 을 통해 실제 Firebase 호출 없이도 최대한 비슷한 환경을 구성하여 단위 테스트를 진행하였습니다. 
-

[FEAT][TEST] FCM 토큰 관리 및 관련 기능 단위 테스트

---

src/main/java/com/gdg/z_meet/domain/fcm/controller/FcmController.java
src/main/java/com/gdg/z_meet/domain/fcm/repository/FcmTokenRepository.java
src/main/java/com/gdg/z_meet/domain/fcm/service/FcmServiceImpl.java
src/main/java/com/gdg/z_meet/domain/user/controller/UserController.java
src/main/java/com/gdg/z_meet/domain/user/service/UserService.java

- #177 
- 
- 로그아웃이 DELETE 타입으로 구현되어 있어서, FCM 토큰이 그렇게 민감한 정보는 아니기도 하고 RESTFUL 하게 파라미터로 넘기려고 했지만 헤더를 커스텀하여 넘기는 방식으로 변경 
- 회원 탈퇴 시, 디바이스 구분 없이 FCM 토큰 전부 삭제 
- 알림 생성 메서드에 사용자 동의 여부에 대한 검증이 빠져 있었어서 추가
-

[REFACTOR] FCM 토큰 전달 방식 쿼리 파라미터 -> 커스텀 헤더로 변경

---

src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
src/main/java/com/gdg/z_meet/domain/meeting/converter/MeetingConverter.java
src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingResponseDTO.java
src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryService.java
src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
src/main/java/com/gdg/z_meet/domain/user/repository/UserRepository.java

- feat/#179_meeting
- 1대1 미팅 로직 구현
- POST /meeting/ONE_TO_ONE API 개발
- 엔티티 변경사항
- UserProfile에 hi, is_visible, verification 컬럼 추가
- 갤러리 조회 시 랜덤 정렬 기능은 다른 브랜치에서 수정하겠습니다 :)
- #179

[FEAT] 1대1 미팅 구현

---

build.gradle
src/main/java/com/gdg/z_meet/domain/chat/service/ChatRoomCommandService.java
src/main/java/com/gdg/z_meet/domain/fcm/feign/FcmFeignClient.java
src/main/java/com/gdg/z_meet/domain/fcm/feign/FcmFeignConfig.java
src/main/java/com/gdg/z_meet/domain/fcm/feign/FcmFeignRes.java
src/main/java/com/gdg/z_meet/domain/fcm/service/FcmMessageClient.java
src/main/java/com/gdg/z_meet/domain/fcm/service/FcmServiceImpl.java
src/main/java/com/gdg/z_meet/domain/fcm/service/custom/FcmChatMessageService.java
src/main/java/com/gdg/z_meet/domain/fcm/service/custom/FcmMeetingMessageService.java
src/main/java/com/gdg/z_meet/domain/meeting/controller/MeetingController.java
src/main/java/com/gdg/z_meet/domain/meeting/dto/MeetingRequestDTO.java
src/main/java/com/gdg/z_meet/domain/meeting/entity/Hi.java
src/main/java/com/gdg/z_meet/domain/meeting/repository/HiRepository.java
src/main/java/com/gdg/z_meet/domain/meeting/repository/HiRepositoryCustom.java
src/main/java/com/gdg/z_meet/domain/meeting/repository/HiRepositoryImpl.java
src/main/java/com/gdg/z_meet/domain/meeting/repository/TeamRepository.java
src/main/java/com/gdg/z_meet/domain/meeting/repository/UserTeamRepository.java
src/main/java/com/gdg/z_meet/domain/meeting/service/HiCommandService.java
src/main/java/com/gdg/z_meet/domain/meeting/service/HiCommandServiceImpl.java
src/main/java/com/gdg/z_meet/domain/meeting/service/HiQueryServiceImpl.java
src/main/java/com/gdg/z_meet/domain/user/entity/User.java
src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
src/main/java/com/gdg/z_meet/domain/user/repository/UserProfileRepository.java
src/main/java/com/gdg/z_meet/global/config/QueryDslConfig.java
src/test/java/com/gdg/z_meet/service/FcmServiceImplTest.java

- #177 
- 
- `미팅`
1. 가입은 했는데, 1일이 지나도 1대1 참여안했을 때 알림
2. 가입은 했는데, 1일이 지나도 2대2 팀 안 만들었을 때 알림
- `1대1`
1. 하이받았을 때 알림
2. 하이 수락시간이 1시간 남았을 때 알림
- `2대2`
1. 하이받았을 때 알림
2. 하이 수락시간이 1시간 남았을 때 알림
API 호출과 연관된 알림들은 호출 시 전송되고, 관련 없이 발송되어야 하는 알림들은 `스케쥴링`을 통해 `백그라운드`에서도 알림이 전송되도록 하였습니다.
1대1 과 2대2의 경우 남은 시간에 대한 정밀한 제어와 다수의 동적인 조건 체킹이 필요했기에 JPQL/Native Query 가 아닌 `QueryDSL` 를 도입하여 구현하였습니다.
-

[FEAT] 1:1 & 2:2 매칭 및 미팅 관련 FCM 알림 구현

---

src/main/java/com/gdg/z_meet/domain/fcm/service/custom/FcmMeetingMessageService.java
src/main/java/com/gdg/z_meet/domain/fcm/service/custom/FcmProfileMessageService.java
src/main/java/com/gdg/z_meet/domain/meeting/entity/Team.java
src/main/java/com/gdg/z_meet/domain/meeting/repository/UserTeamRepository.java
src/main/java/com/gdg/z_meet/domain/meeting/service/MeetingQueryServiceImpl.java
src/main/java/com/gdg/z_meet/domain/user/entity/UserProfile.java
src/main/java/com/gdg/z_meet/domain/user/repository/UserProfileRepository.java

- #197 
- 
- 1:1 과 2:2 상황에서 갤러리 조회 시 뜨는 프로필에 대한 조회 수 알림을 구현하였습니다. 
-

[FEAT] FCM 1:1 & 2:2 프로필 조회 수 관련 알림 구현

---

src/main/java/com/gdg/z_meet/global/config/RedisConfig.java

- #230 
[문제가 되었던 설정들] 
- `DefaultTyping.NON_FINAL` :  DTO와 같은 모든 final이 아닌 타입에 대해 다형성 처리를 활성화
- `As.PROPERTY` : 타입 정보를 JSON 내부의 @class 속성으로 명시하라고 요구
즉, 해당 설정으로 모든 non-final 객체를 역직렬화 시, JSON에 "@class": "com.xxx.YourType" 같은 정보가 있어야 동작했었음
따라서 해당 설정 제거 
- 
-

[FIX] 역직렬화 오류로 인한 ObjectMapper 설정 수정

---

src/main/java/com/gdg/z_meet/domain/meeting/repository/HiRepository.java
src/main/java/com/gdg/z_meet/domain/meeting/service/HiQueryServiceImpl.java

- fix/#250_hi
- 받은 하이, 보낸 하이 조회 시 다른 유저 데이터도 같이 조회되는 에러 해결
- 하이 타입에 따라서 조회하는 인덱스 변경
- 수정 전: 팀 아이디 리스트에 유저 아이디 추가 후, 하이 타입 구분없이 리스트에 해당하는 모든 하이 조회
-> 유저 아이디가 1일 경우, 인덱스가 1에 해당하는 1대1, 2대2 하이를 모두 조회하는 문제 발생
- 수정 후: 하이 타입에 따라 각각 팀 아이디와 유저 아이디로 구분하여 조회
- #250 
수정 전
수정 후

[FIX] 하이 리스트에서 다른 유저 데이터 조회
